aqjune/mlir-tv

CMakeLists.txt
README.md
tests/lit.cfg.py
tests/lit/formats/__init__.py
tests/lit/formats/mlirtest.py
tests/opts/README.md

This PR applies the changed project name to binary name and documentations.
- All `iree-tv`s are now renamed into `mlir-tv`s.

Renamed to mlir-tv in tests, comments, and READMEs

---

src/vcgen.cpp

By default, `size > 0` is encoded into `bvsgt` (which means signed-greater-than).
So we explicitly encode using `z3::ugt`when check size inbounds.
```
(=> (bvsgt dim.3 #x00000000) (bvult (bvadd dim.3 #xffffffff) dim.3))
(=> (bvsgt dim.4 #x00000000) (bvult (bvadd dim.3 #xffffffff) dim.4))
```
```
(=> (bvugt dim.3 #x00000000) (bvult (bvadd dim.3 #xffffffff) dim.3))
(=> (bvugt dim.4 #x00000000) (bvult (bvadd dim.3 #xffffffff) dim.4))
```

Use z3::ugt rather than z3::sgt

---

src/state.cpp
src/state.h
src/vcgen.cpp
tests/litmus/memref-ops/buffer_cast.src.mlir

QF_UFBV(Unquantified formulas over bitvectors with uninterpreted sort function and symbols) logic fails when expression has  quantifier.
So we select z3 solver logic dynamically based on expression.
`forall` quantifier could be introduced when encoding `memref::buffer_cast` operation.

Use UFBV logic when expression has Quantifier

---

CMakeLists.txt
README.md
unittests/CMakeLists.txt

This PR changes the CMake configuration to change dependency of `mlir-tv` from IREE to MLIR.
- Now accepts `MLIR_DIR` instead of `IREE_DIR` and `IREE_BUILD_DIR`
- unittests CMakeLists now derive include and lib directories from iree-tv CMakeLists
- Updated README

Update CMakeLists to change dependencies

---

CMakeLists.txt
src/state.h
src/value.h
src/vcgen.cpp

This PR fixes compile failures when using the latest stdlib (to be precise, libstdc++ 11.2)
Some files that use `std::optional<T>` were missing header `<optional>`. This still worked in the older stdlibs, but it seems the libraries have since been refactored and doesn't compile anymore.
Resolved this issue by simply adding headers in each file.
Also, the `MLIRInferTypeOpInterface` and `MLIRViewLikeInterface` library were written twice in CMakeLists. Deduped both libraries.

Fix compile failures in latest c++ stdlibs

---

src/main.cpp
src/memory.cpp
src/memory.h
src/state.cpp
src/value.cpp
src/value.h
src/vcgen.cpp

To solve memory mismatch issue in `buffer_cast` operations, we introduce a new concept of memory block. 
That is "local memory block" which can exist only in that block scope.
So there blocks published dynamically at runtime and block size is determined at that time.
For simplicity, local memory blocks are not considered when showing refinement between memory for now.

Implement local memory blocks

---

src/memory.cpp
src/memory.h
src/value.cpp
src/value.h
src/vcgen.cpp
tests/litmus/memref-ops/buffer_cast.src.mlir
tests/litmus/memref-ops/var_buffer_cast.src.mlir
tests/litmus/memref-ops/var_buffer_cast.tgt.mlir

In the previous PR (https://github.com/aqjune/mlir-tv/pull/66), we encoded buffer_cast ops using a forall quantifier.
However, using a forall quantifier is expensive in SMT.
But, in many cases, we can find a cheaper encoding for buffer_cast.
If the origin memref is identity-mapped, it can be encoded more efficiently using `z3::lambda`.
Memref with an identity map means its layout is same as that of the origin tensor.
By using lambda, transformations containing complex buffer_cast operations (variable sized tensor, multi-dimension..) are verified much faster than before.
In the previous encoding, even verifying very small memrefs like `memref<3x4xf32>` failed.

Improve buffer_cast encoding when memref has an identity map

---

src/value.cpp
src/value.h
src/vcgen.cpp

To make it clear that `BufferCastOp` creates a new local memory block, we remove freshBlock parameters.
And we explicitly call `addLocalBlock` to memory when encoding BufferCastOp.
In this way, we keep the consistency that the memref points a already existing block id.

Detach freshBlock parameter in MemRef 

---

CMakeLists.txt

This PR fixes recent issue regarding the cmake -D variables
- Cmake -D arguments now correctly set paths

Fix issue with cmake -D variables

---

src/vcgen.cpp

The output instruction is not ordered, so it's hard to understand what it actually means.
So in this PR, we update the ordering of instruction based on input MLIR code.
```
func @fold_tensor_extract(%arg0 : memref<2x3xf32>) -> f32
{
%c1 = constant 1 : index
%c2 = constant 2 : index
%0 = memref.tensor_load %arg0 : memref<2x3xf32>
%1 = tensor.extract %0[%c1, %c2] : tensor<2x3xf32>
return %1 : f32
}
```
```
Function fold_tensor_extract
<src>
%c1 = constant 1 : index
%c1_0 = constant 1 : index
%0 = memref.tensor_load %arg0 : memref<2x3xf32>
%1 = tensor.extract %0[%c1, %c1_0] : tensor<2x3xf32>
return %1 : f32
<tgt>
%c1 = constant 1 : index
%c2 = constant 2 : index
%0 = memref.load %arg0[%c1, %c2] : memref<2x3xf32>
return %0 : f32
== Result: Return value mismatch
<Inputs>
arg0: (bid: arg0_bid, …
```

Print counter example instruction in pretty format

---

src/smt.cpp
src/smt.h

This PR presents a proof-of-concept expr wrapper class, `smt::Expr`.
This class has three major goals as of now:
- Hide away solver-specific interface as much as possible
- Prevent potential performance degradation while dealing with many expressions
- Reduce the complexity of supporting new solvers
This class doesn't have enough methods to be fully functional, so it hasn't replaced any `z3::expr`s yet.

Implement prototype smt::Expr

---

src/value.cpp
src/value.h
src/vcgen.cpp

In this PR, we support memref.subview encoding.
Memref subview operation makes an alias object of original memref with different offset, sizes, strides.
The detailed subview behavior can be found in [documents](https://mlir.llvm.org/docs/Dialects/MemRef/#memrefsubview-mlirmemrefsubviewop).
The basic calculation logic is like this. (offsets, sizes, strides are parameters of subview operation)
```
// Before : <(d0, d1) -> (d0 * s0 + d1)>,
// After: <(d0, d1) -> ((d0 + offsets[0]) * strides[0] * s0 + (d1 + offsets[1]) * strides[1])>
```
The result memref layout information are also doubly checked by MLIR verifier whether it matches with expected value.
(see `Type SubViewOp::inferResultType` in MLIR code)

Encode subview parameters and calculate transformed layout

---

src/value.cpp
src/value.h
src/vcgen.cpp

In this PR, we added inbounds check for SubViewOp
In documents, there's comments about how memref bounds are defined.
```
// Note that the subview op does not guarantee that the result
// memref is "inbounds" w.r.t to base memref. It is upto the client
// to ensure that the subview is accessed in a manner that is
// in-bounds.
```
To carefully deal with this inbounds check, the every memref's Layout should carry this inbounds information.
Then result memref bounds are determined from the source's memref information. 
For example,
```C
%0: memref<2x3xf32>
// %0's Layout is defined..
// layout.indVars = d0, d1
// layout.expr = d0 * 3 + d1
// layout.inbounds = d0 < 2 && d1 < 3
%1 = memref.subview %0[0, 0][2, 2][2, 1] : 
memref<2x3xf32> to memref<2x2xf32, affine_map<(d0, d1) -> (d0 * 3 * 2 + …
```

Encode memref inbounds check for SubViewOp when load, store memory

---

src/value.cpp
src/value.h
src/vcgen.cpp
tests/litmus/memref-ops/subview_reduce_rank.src.mlir
tests/litmus/memref-ops/subview_reduce_rank.tgt.mlir

In this PR, we additionally encode rank reduced cases of subview operation.
In MLIR [documents](https://mlir.llvm.org/docs/Dialects/MemRef/#memrefsubview-mlirmemrefsubviewop), A subview operation may additionally reduce the rank of the resulting view by removing dimensions that are statically known to be of size 1.
So after comparing source and result memref's rank, we can remove dimension if its size is statically known to be 1.
This process should be done while traversing dimension in increasing order, as in SubViewOp in MLIR (see `Type SubViewOp::inferRankReducedResultType` in MemRefOps.cpp)

Implement memref.subview rank reduction cases

---

CMakeLists.txt
src/smt.cpp
src/smt.h
src/utils.h

This PR implements two new wrapper classes for solvers
- ~~`ExprVec` is a wrapper for vector of `Expr`s.~~ Removed
- `Context` is a wrapper for solver contexts.
Also, new semantics for `Expr` has been introduced
- `Expr`s cannot be constructed using constructors: instead, class static methods construct commonly used values.
Also, in order to reduce the mental load of tracking down aliases and mutations, `Expr` objects...
- are immutable: every methods create a new object instead of mutating itself
- ~~cannot be copy-assigned: one must use `clone()` method to do so, making sure that user acknowledges the object is being copied.~~ Excluded as of now
- ~~clearly distinguishes move and copy: this makes reasoning about aliases easier (*because there's virtually no alias*), reduces confusion, …

Implement more solver-independent wrappers

---

src/smt.cpp
src/smt.h

This PR implements a wrapper class `smt::Sort` for solver-independent sorts.
- Implement class `Sort`
- Implement additional `mk*` methods using `Sort`
- Limit line length to ~80 chars

Implement `smt::Sort`

---

CMakeLists.txt

This PR adds some more linker options to use topology sort when linking libraries.
More recent linkers such as LLD automatically sorts libraries prior to linking process, but older ones should be given an explicit order to do so. This change has turned out successful on GNU LD, which previously failed to link libraries.

Fix linking issue on linkers without automatic tsort

---

src/smt.cpp
src/smt.h
src/state.cpp
src/state.h
src/value.cpp
src/value.h
src/vcgen.cpp

Before we support various memref operations, we need the definition of inverseMapping of layout map.
This is because many arithmetic operations like conv, add, mul can be encoded more easily and efficiently if we abstract concrete MemRef's layout.
In other words, it is much simpler to find the expression for %memref[i][j] and then encode it in memory by giving concrete layout information.
In this PR, we changed to use lambda when encoding layout to better express that is a function.
And add new inverseMappings which represent inverse function of layout mapping.
These will be used later when we support additional memref operations.
Since there is no operation that uses inverseMappings yet, nothing changed from current smt encoding.
I also checked `ctest` works well without problems.

Add inverseMappings to MemRef Layout encoding

---

src/smt.cpp
src/smt.h

This PR implements generic solver and result class to support using multiple solvers.
As of now, `Solver` class only supports `add(Expr)`, `reset()`, and `check()`. I looked into previous uses of z3::solver and assumed we don't use much more than these three. (And yet we can implement more methods when they become necessary)
`Result` class is a one-on-one replacement for SMT result, and supports basic comparison.

Implement wrapper class for solver and result

---

CMakeLists.txt

This PR fixes the linker issue in Apple platform due to https://github.com/aqjune/mlir-tv/pull/99.
Apple LLD does not support `--start-group` and `--end-group` flags, so these flags won't be added when Apple platform is detected.

Add platform-specific linking options in CMakeLists

---

CMakeLists.txt
README.md
src/smt.cpp
src/smt.h

This PR adds SOLVER-<solver> macros and updates CMakeLists to allow linking against CVC5.
README is updated as well.

Cherry-pick solver-macros, CMakeLists, and README

---

src/encode.cpp
src/print.cpp
src/value.cpp
src/value.h

In this PR, we make a common class of Tensor, MemRef class which contains common index (dimension) based logic.
Maybe linalg operations related with both Tensor, MemRef are fit here.
These operations will be added in following PR.

Make Tensor, MemRef class inherit Shaped class

---

src/encode.cpp
src/value.cpp
src/value.h
tests/litmus/linalg-ops/convolution.src.mlir
tests/litmus/linalg-ops/convolution.tgt.mlir

In this PR, we added `linalg::conv`operations encoding.
Main convolution calculation is done by `ShapedValue::conv`, and memref's conv operation just store result values into Memory.
For simplicity, currently we support only plain layout mapped MemRef.
This constraint may be relaxed later..

Support linalg::conv encoding

---

src/encode.cpp
src/value.cpp
src/value.h
tests/litmus/memref-ops/subview_out_of_bounds.src.mlir
tests/litmus/memref-ops/subview_out_of_bounds.tgt.mlir
tests/opts/fold-memref-subview-op/rank_reduction.src.mlir
tests/opts/fold-memref-subview-op/rank_reduction.tgt.mlir

From mlir-testsuites, we found three bugs in subview encoding.
Before : <(d0, d1) -> (d0 * s0 + d1)>,
After: <(d0, d1) -> ((indVars[0] + offsets[0]) * strides[0] * s0 + (indVars[1] + offsets[1]) * strides[1])> ➡️ ❌
After: <(d0, d1) -> ((indVars[0] * strides[0] + offsets[0]) * s0 + indVars[1] * strides[1] + offsets[1])>.  ➡️ ⭕
Related information can be found in `MemRef/Trnasforms/FoldSubViewOps.cpp`.
```
//===----------------------------------------------------------------------===//
// Utility functions
//===----------------------------------------------------------------------===//
/// Given the 'indices' of an load/store operation where the memref is a result
/// of a subview op, returns the indices w.r.t to the source memref of the
/// subview op. For example
///
/// %0 = ... : …
```

Fix bugs in subview encoding

---

src/encode.cpp
src/value.cpp
tests/opts/llvmcpu-plan-conv-loop-order/simple-small.src.mlir
tests/opts/llvmcpu-plan-conv-loop-order/simple-small.tgt.mlir

Add MemRef related encoding for linalg.generic loop.
And we finally verify `llvmcpu-plan-conv-loop-order` optimization!
```
Test project /Users/makesource/src/mlir-tv/build
Start  1: Opts-conv2d-to-img2col
1/16 Test  #1: Opts-conv2d-to-img2col ..............   Passed    2.32 sec
Start  2: Opts-fold-memref-subview-op
2/16 Test  #2: Opts-fold-memref-subview-op .........   Passed    0.59 sec
Start  3: Opts-fold-tensor-extract-op
3/16 Test  #3: Opts-fold-tensor-extract-op .........   Passed    2.01 sec
Start  4: Opts-fusion-tensor
4/16 Test  #4: Opts-fusion-tensor ..................   Passed    3.28 sec
Start  5: Opts-llvmcpu-plan-conv-loop-order
5/16 Test  #5: Opts-llvmcpu-plan-conv-loop-order ...   Passed  172.78 sec
Start  6: Litmus-abstraction
6/16 Test  #6: Litmus-abstraction …
```

Support linalg::generic encoding for memref

---

CMakeLists.txt

This PR fixes build failure when using latest MLIR by linking additional library.

Fix compile failure in latest MLIR

---

src/encode.cpp
tests/litmus/linalg-ops/dot_commutative.src.mlir
tests/litmus/linalg-ops/dot_commutative.tgt.mlir

Support this type of `linalg.generic` loop.
Because addf is commutative ops, `%res2 = addf %s, %res : f32`, `%res2 = addf %res, %s : f32` is encoded into same SMT expression. 
```
%result = linalg.generic {
indexing_maps = [affine_map<(d0) -> (d0)>,
affine_map<(d0) -> (d0)>,
affine_map<(d0) -> ()>],
iterator_types = ["reduction"]}
ins(%a, %b : tensor<100xf32>, tensor<100xf32>)
outs(%outty : tensor<f32>) {
^bb0(%ai : f32, %bi: f32, %res : f32):
%s = mulf %ai, %bi: f32
%res2 = addf %s, %res : f32
linalg.yield %res2 : f32
} -> tensor<f32>
```

Support commutative sum in linalg.generic

---

src/smt.cpp

This PR fixes a bug in Expr::isIdentical() method when linking against mutiple solvers.
When the `mlir-tv` is linked against multiple solvers but does not actually use them (e.g. not using `--cross-check`), and the `is_or` is set to false, the method always returns false. This doesn't look like an intended behavior.
This has been fixed so that the unused solver(s) do not affect the return value.

Fix issue with Expr::isIdentical()

---

src/abstractops.cpp
tests/litmus/identity/mul.src.mlir
tests/litmus/identity/mul.tgt.mlir
tests/litmus/identity/mul_const.src.mlir
tests/litmus/identity/mul_const.tgt.mlir

This PR updates `aop::fpMul` in order to implement fmul identity behavior
- `aop::fpMul` operation now returns rhs/lhs if the value of lhs/rhs is identical to Float(1.0)
- Litmus tests are added to show the changed behavior

Implement multiplication identity behavior for `aop::fpMul`

---

src/abstractops.cpp
src/abstractops.h
src/smt.cpp
src/value.cpp
src/vcgen.cpp
tests/litmus/linalg-ops/dot_associativity2.src.mlir
tests/litmus/linalg-ops/dot_associativity2.tgt.mlir

Encode `sum_fn`'s associativity by using uninterpreted function.
`sum_fn`'s equality is given by preconditions which are built when encoding src, tgt smt arrays.
We only add equality conditions when two smt arrays have same length to reduce the number of candidate pairs.
For each candidate pairs, we use distinct `hashfn`s to check whether they can be hashed into different values.

Encode sum_fn's associativity using uninterpreted hash function

---

src/abstractops.cpp

This PR is a NFC to keep consistency between parameter names in functions.
`aop::fpAdd` accepts `f1` and `f2` as its function parameter, and so does `aop::fpMul` in its declaration in `abstractops.h`. However, the function definition used to call them `a` and `b`.
I changed them into `f1` and `f2`

change parameter names of `aop::fpMul`

---

src/encode.cpp
src/value.cpp
src/value.h
tests/litmus/tensor-ops/insert.src.mlir
tests/litmus/tensor-ops/insert.tgt.mlir
tests/litmus/tensor-ops/insert_bad.src.mlir
tests/litmus/tensor-ops/insert_bad.tgt.mlir

Implemented `tensor.insert` operation which allows to create new tensor based on original value.
Because tensor is immutable type, this operation always create new tensor value.

Implement tensor.insert operation

---

src/smt.cpp

In cvc5, the solver interprets bit-vector and numeral types are different.
This causes problems when checking whether SMT array is constant sized. 
So in this pr, I fixed it to treats bit vector as numeral as is in Z3 SMT solver.

Fix numeral related bugs in cvc5

---

src/abstractops.cpp
src/abstractops.h
src/encode.cpp
src/value.cpp
src/value.h

This PR changes `double` to `float` where their uses are related to `Float` class.
* `Float`s are now initialized using `float`
* `Float`s are now managed by maps that use `float` as their key

Use `float`(f32) instead of `double`(f64) in `Float`

---

src/value.cpp

- Resolved unused variable (`Wunused-variable`) warnings
- Resolved control flow reaches end of non-void function (`Wreturn-type`) warnings

Resolve compiler warnings

---

src/main.cpp
src/smt.h

To compare each solver's performance, we support cvc5-only running option.
You can give solver options like this. 
`./mlir-tv <src>.mlir <tgt>.mlir --solver=CVC5`
Currently, default value of this option is Z3 only.

Support cvc5-only running

---

src/abstractops.cpp

Because there's no performance degradation when validating, we extend 4-bits abstract values to 32-bits abstract values.
This means we can support more various kind of programs which contain more than 16(=2^4) distinct floating number.

Support 32-BITS distinct floating point value

---

src/abstractops.cpp
src/abstractops.h
src/main.cpp
src/vcgen.cpp
src/vcgen.h

Revert previous multi sets encoding in https://github.com/aqjune/mlir-tv/pull/125.
But in previous PR, bag equality with uninterpreted function is not well supported in CVC5..
To resolve this issue, I added bag equality precondition in `getAssociativePrecondition()` and this works well!
cf. Currently CVC5 support ackermannization in very limited condition. So I just encoded it in precondition :(

Revert multiset encoding for benchmark 

---

src/encode.cpp

Fix appropriate type conversion from `ValueTy` to `Expr` using getExpr()

Fix crash in constant op encoding

---

.github/workflows/env.yml

This PR fixes the bug in CI environment image update script.
* Reported issue: LLVM in the docker image created by `Daily-update` action is outdated
* Reason: When building the image, the action runner kept fetching the older Z3/cvc5/LLVM cache. This was due to misconfiguration in the script's cache fall-back behavior.
* Fix: Instead of using cache fallback, the action runner will now identify and fetch the correct cache using the commit hash of Z3/cvc5/LLVM.

Fix bug in Daily-update action

---

src/analysis.cpp
src/encode.cpp

The recently updated `mlir::Attribute` API has introduced some breaking changes.
- `get[.+]Value(mlir::ArrayRef<T> indices)` are now changed into `getValues()[mlir::ArrayRef<T> indices>]`

Catch up with updated MLIR

---

src/analysis.cpp
src/analysis.h
src/vcgen.cpp

This PR implements precision-sensitive FP counting.
- F32 and F64 constants/variables are counted separately
- Each F32 and F64 constant found is also added respectively to F64 and F32 constant list, with possible rounding if necessary.

Implement more precise fp counting

---

src/abstractops.cpp
src/abstractops.h

This PR refactors and renames variables in `AbsFpEncoding` to clarify the semantics of each variable.
- Rename `...bv_bits` to `...bitwidth`
- Rename `valuebit` to `smaller_value_bitwidth` to eliminate the confusion between`value_bitwidth` and `valuebit`
- Group limit/smaller_value/prec bits into `ValueBitInfo` struct to clarify the relationship between these three bvs and value bv.

Refactor `AbsFpEncoding`

---

src/abstractops.cpp
src/abstractops.h

This PR introduces a new FP bitwidth calculation method.
- If FP casting abstraction level is `FULLY_ABS`, each `AbsFpEncoding` is constructed as following:
- Both limit and precision bitwidth are set to 0.
- Smaller value bitwidth is calculated as `log2_ceil(#variables + #constants + 2)`
- If FP casting abstraction level is `PRECISE`, there's a whole new policy to decide each bitwidth. It is somewhat complex to explain in PR description, so please refer to paper repo for more information.

Improve fp bitwidth calculation policy

---

src/abstractops.cpp
src/abstractops.h

This PR removes redundant variable and related constructors.

Remove `AbsFpEncoding::smaller_fpty_enc`

---

src/abstractops.cpp
src/abstractops.h
src/encode.cpp
src/value.cpp
src/value.h
tests/litmus/fp-ops/comm_div-bad.src.mlir
tests/litmus/fp-ops/comm_div-bad.tgt.mlir
tests/litmus/fp-ops/comm_div_const-bad.src.mlir
tests/litmus/fp-ops/comm_div_const-bad.tgt.mlir
tests/litmus/fp-ops/ident_div.src.mlir
tests/litmus/fp-ops/ident_div.tgt.mlir
tests/litmus/fp-ops/ident_div_const.src.mlir
tests/litmus/fp-ops/ident_div_const.tgt.mlir
tests/litmus/fp-ops/inf_div_const.src.mlir
tests/litmus/fp-ops/inf_div_const.tgt.mlir
tests/litmus/fp-ops/inf_div_const_neg.src.mlir
tests/litmus/fp-ops/inf_div_const_neg.tgt.mlir
tests/litmus/fp-ops/inf_div_inf.src.mlir
tests/litmus/fp-ops/inf_div_inf.tgt.mlir
tests/litmus/fp-ops/inf_div_zero.src.mlir
tests/litmus/fp-ops/inf_div_zero.tgt.mlir
tests/litmus/fp-ops/nan_div.src.mlir
tests/litmus/fp-ops/nan_div.tgt.mlir
tests/litmus/fp-ops/zero_div_const.src.mlir
tests/litmus/fp-ops/zero_div_const.tgt.mlir
tests/litmus/fp-ops/zero_div_zero.src.mlir
tests/litmus/fp-ops/zero_div_zero.tgt.mlir

This PR implements abstract FP division (aka `smt::Expr AbsFpEncoding::div()`)
- If one or more operand of div is NaN, it yields NaN as well.
- 0.0 / 0.0 and Inf / Inf yields NaN.
- finite x / Inf yields 0.0
- Inf / finite x yields Inf
- Finite x / 0.0 yields Inf.  
This is division by zero and signaling exception should be raised according to IEEE754 standard, but LLVM ignores the signal and continues the execution. We follow this semantics as well.
- Otherwise, it yields an arbitrary BV with appropriate sign.
- Litmus tests are added to verify the above behaviors

Implement FP division

---

src/abstractops.cpp

Some sort variables in abstractops.cpp are defined using `Sort::mkBV(fp_bitwidth)` or `Sort::mkBV(tgt.fp_bitwidth)`.
Using `AbsFpEncoding::sort()` seems more straightforward in these cases.

Use `AbsFpEncoding::sort()` wherever more desirable

---

src/abstractops.cpp
src/abstractops.h
src/analysis.cpp
src/smt.cpp
src/vcgen.cpp
tests/litmus/fp-ops/trunc_const_rounding.src.mlir
tests/litmus/fp-ops/trunc_const_rounding.tgt.mlir
tests/litmus/fp-ops/trunc_const_to_inf.src.mlir
tests/litmus/fp-ops/trunc_const_to_inf.tgt.mlir

This PR implements precondition-based rounding FP truncation.
- The values being truncated are now properly 'rounded' instead of being 'floored`.
- FP truncation is now implemented based on UF and preconditions
- FP constant analysis adds preconditions, which limits the possible value of each truncated constant to a single value
- `AbsFpEncoding::truncate()` adds preconditions, which limits the possible value of each truncated variable to 'floored' and 'ceiled' value. 
- In case there are more than one possible truncation result, other preconditions may be added in the future to choose one of them.
- Fixed several bugs in previous truncation behaviors
- Litmus tests are added to verify the behaviors described above

Implement precise FP rounding

---

src/encode.cpp
tests/litmus/linalg-loops/sum-assoc-bad.src.mlir
tests/litmus/linalg-loops/sum-assoc-bad.tgt.mlir
tests/litmus/linalg-loops/sum-assoc.src.mlir
tests/litmus/linalg-loops/sum-assoc.tgt.mlir
tests/litmus/linalg-ops/tensor_expand_shape.src.mlir
tests/litmus/linalg-ops/tensor_expand_shape.tgt.mlir
tests/litmus/tensor-ops/fold_collapse_collapse.src.mlir
tests/litmus/tensor-ops/fold_collapse_collapse.tgt.mlir
tests/litmus/tensor-ops/fold_expand_collapse.src.mlir
tests/litmus/tosa-ops/reduce_sum-bad.src.mlir
tests/litmus/tosa-ops/reduce_sum-bad.tgt.mlir
tests/litmus/tosa-ops/reduce_sum_int-bad.src.mlir
tests/litmus/tosa-ops/reduce_sum_int-bad.tgt.mlir
tests/long-opts/conv2d-to-img2col/nhwc_filter-bad.tgt.mlir
tests/opts/conv2d-to-img2col/nhwc_filter.tgt.mlir
tests/opts/linalg-fold-unit-extent-dims/one-trip-loop.tgt.mlir
tests/opts/tosa-to-linalg/reduce_sum.tgt.mlir
tests/opts/tosa-to-linalg/reduce_sum2.tgt.mlir
tests/opts/tosa-to-linalg/tile.tgt.mlir

There has been a breaking change in MLIR API.
* linalg::TensorExpandShapeOp -> tensor::ExpandShapeOp
* linalg::TensorCollapseShapeOp -> tensor::CollapseShapeOp

Catch up with MLIR API update

---

src/abstractops.cpp
src/abstractops.h
src/encode.cpp
src/value.cpp
src/value.h
tests/litmus/fp-ops/cmp_const-bad.src.mlir
tests/litmus/fp-ops/cmp_const-bad.tgt.mlir
tests/litmus/fp-ops/cmp_const.src.mlir
tests/litmus/fp-ops/cmp_const.tgt.mlir
tests/litmus/fp-ops/cmp_fixed.src.mlir
tests/litmus/fp-ops/cmp_fixed.tgt.mlir
tests/litmus/fp-ops/cmp_inverse.src.mlir
tests/litmus/fp-ops/cmp_inverse.tgt.mlir
tests/litmus/fp-ops/cmp_nan.src.mlir
tests/litmus/fp-ops/cmp_nan.tgt.mlir
tests/litmus/fp-ops/cmp_ord-bad.src.mlir
tests/litmus/fp-ops/cmp_ord-bad.tgt.mlir
tests/litmus/fp-ops/cmp_zero.src.mlir
tests/litmus/fp-ops/cmp_zero.tgt.mlir
tests/litmus/tensor-ops/cmp_const.src.mlir
tests/litmus/tensor-ops/cmp_const.tgt.mlir
tests/litmus/tensor-ops/cmp_inverse.src.mlir
tests/litmus/tensor-ops/cmp_inverse.tgt.mlir

This PR implements comparison operator for float types.
- cmp is implemented as a set of concrete ite expressions. Each expression yields a BV(1) from two BV(fp_bitwidth)s.
- Using cmp looks like this: `cmp(pred, f1, f2)`
- `pred` is an enum class `aop::CmpPredicate`. There are 16 members in `aop::CmpPredicate`, and each represents the corresponding cmpf predicate in MLIR. (`[Ordered|Unordered][EQ|NE|LE|LT|GE|GT], Ordered, Unordered, True, False`) 
- Litmus tests are added to verify the behavior.

Implement cmpf operator

---

tests/litmus/fp-ops/ext_cmp.src.mlir
tests/litmus/fp-ops/ext_cmp.tgt.mlir

This PR adds litmus tests for extf operation
- `cmpf extf(a), extf(b)` == `cmpf a, b`

Litmus tests for cmpf after extension

---

src/abstractops.cpp

The magnitude bitwidth of float should not exceed 31, because it should not use more bits than real-life float

Restrict `floatBits` to maximum 31

---

src/abstractops.cpp
tests/litmus/fp-ops/self_div_const.src.mlir
tests/litmus/fp-ops/self_div_const.tgt.mlir
tests/litmus/fp-ops/zero_div_const.src.mlir
tests/litmus/fp-ops/zero_div_const.tgt.mlir

This PR implements two important properties of FP division (which was missing)
- +-0.0 / x -> ?0.0 (x != +-0.0)
- x / x -> 1.0, x / -x -> -1.0 (x != +-0.0 or +-Inf)

Implement missing semantics for fp div

---

.github/workflows/env.yml

This PR updates the CI script to only use the stabilized version of smt solvers.

Only use stable tags for solvers

---

.github/workflows/env.yml
README.md

In order to enhance stability and avoid possible breaking changes in the future, we'll stay on the latest(as of now) versions of LLVM, z3, and cvc5 for a while. Please refer to README for more details.

Disable automatic CI image update

---

src/value.cpp

`zero()` returns non-negative zero value

Fix fp identity in to1DArrayWithOfs

---

src/value.cpp
src/value.h
src/vcgen.cpp

If we validate multiple source, target fn pairs, this creates iill-formed expression

Reset abstractlyEncodedAttrs for each fn pair

---

src/encode.cpp
src/value.cpp
src/value.h

Also move MemRef::conv to encode.cpp because it is using MemRef::storeArray

Remove MemRef::storeArray because it is layout-unsafe

---

src/abstractops.cpp

Due to a pitfall in our FP encoding, truncating a value of which TB == INT_MAX yields NaN although the original value is some finite value.
Therefore, even if LB == 0, truncate() now explicitly yields Inf if the TB >= INT_MAX - 1.
Also, constants beyond LFP's range may be assigned a BV of which LB == 0 and TB >= INT_MAX - 1.

Fix issue where truncate() may unexpectedly yield NaN

---

src/vcgen.cpp

In previous decision (https://github.com/aqjune/mlir-tv/pull/125),
`useAllLogic` is related with `vinput.isFpAddAssociative` because it uses "multiset theory" and "constant array".
But now, we use "QF_AUFBV" logic in Z3 and "HO_ALL" logic in CVC5 by default, we do not need to use all logic when vinput.isFpAddAssociative is given.

Fix useAllLogic is always on when vinput.isFpAddAssociative

---

.github/workflows/env.yml
README.md

Due to API bugs introduced in cvc5 0.0.4, we're falling back to cvc5 0.0.3 until this issue is resolved

Use cvc5 0.0.3 in CI

---

src/smt.cpp

cvc5 distinguishes logical and BV xor, but `Expr::operator^` only uses BV xor.
This PR fixes the implementation so that it uses the correct operator for each case.

Fix cvc5 implementation of `Expr::operator^`

---

src/smt.cpp

Allowing multiple smt variables of same name is error-prone and undesirable.
This is no longer allowed when using cvc5, unless the `smt::Solver` that created the variables is destructed.

Fix smt interface for cvc5

---

src/abstractops.cpp

In imprecise casting mode, float and double may share the same smt variable. This may allow false assumption for smt solver, so this PR changes the name of smt variables that double uses in such case.

Double in imprecise casting mode use different vars

---

src/abstractops.cpp
src/abstractops.h

This PR assigns the largest possible VALUE_BITS for the float::MAX (f32::MAX, f64::MAX, ...) to ensure that no other finite numbers are larger than it.
Although the term is float::MAX, this also applies to -float::MAX (note that this is different from float::MIN : the latter means the float number with smallest magnitude)

Reserve max VALUE_BITS for float::MAX

---

src/encode.cpp
src/value.cpp
src/value.h

This PR fixes the issue where encoding `mlir::tensor::FromElementsOp` crashed upon encountering zero-dim tensor situation.
If the operand is not given and the return type is 0-dim tensor, 0-dim `Tensor` of Op return type is created

Add zero-dimension tensor support for `mlir::tensor::FromElementsOp`

---

src/encode.cpp

* Pooling only supports FP in mlir-tv: raise UnsupportedException for non-FP tensors
* ElementwiseBinOp only supports operation between operands of the same type: raise UnsupportedException for tosa::FullyConnectedOp with operands of different type tensors

Fix crashes from Conversion tests

---

CMakeLists.txt

Recent update in MLIR requires libMLIRQuantUtils to be linked to `mlir-tv`

Fix link failure

---

CMakeLists.txt

Seems like building the tool with llvm trunk requires adding MLIRControlFlow library

fix link error during build

---

tests/lit/formats/mlirtest.py
tests/litmus/diagnostics/assign-random.src.mlir
tests/litmus/linalg-ops/memref_matmul_bad.src.mlir
tests/litmus/memref-ops/nonidentity-layout-store-bad.src.mlir
tests/litmus/memref-ops/nonidentity-layout-store.src.mlir
tests/litmus/refinement/size-mismatch.src.mlir
tests/opts/README.md

This PR updates lit test script for `mlir-tv` to support more sophisticated testing.
- When `mlir-tv` crashes due to segmentation fault, lit test now raises FAIL and show stderr instead of throwing exception.
- Updated keywords and test features are described in README.

New test keywords for `mlir-tv`

---

tests/README.md
tests/lit/formats/mlirtest.py

- Test code are formatted according to [PEP8](https://www.python.org/dev/peps/pep-0008/) guideline.
- Whitespace of an arbitrary length is allowed between `//` and the test keyword.
- README is moved from tests/opts to tests directory.

Minor test script fixes

---

src/analysis.cpp

GenericOp accepts memref argument as input & output and newly created FPs can be stored to output memref.
So we also count that values in analysis.cpp

Analyze FPs from linalg::generic outputs

---

tests/litmus/abstraction/dotint.tgt.mlir
tests/litmus/bufferization-ops/fill-memref-bad.tgt.mlir
tests/litmus/bufferization-ops/fill-memref.tgt.mlir
tests/litmus/linalg-ops/dot.src.mlir
tests/litmus/linalg-ops/dot.tgt.mlir
tests/litmus/linalg-ops/dot2.src.mlir
tests/litmus/linalg-ops/dot2.tgt.mlir
tests/litmus/linalg-ops/dot_commutative.tgt.mlir
tests/litmus/linalg-ops/dot_rewrite_manually.src.mlir
tests/litmus/linalg-ops/dot_rewrite_manually.tgt.mlir
tests/litmus/linalg-ops/dot_rewrite_manually_assoc.src.mlir
tests/litmus/linalg-ops/dot_rewrite_manually_assoc.tgt.mlir
tests/litmus/linalg-ops/fill.src.mlir
tests/litmus/linalg-ops/fill.tgt.mlir
tests/litmus/linalg-ops/memref_matmul.src.mlir
tests/litmus/linalg-ops/memref_matmul.tgt.mlir
tests/litmus/linalg-ops/pooling_unsupported2.src.mlir
tests/litmus/linalg-ops/pooling_unsupported2.tgt.mlir
tests/long-opts/tosa-to-linalg/conv2d2.tgt.mlir
tests/long-opts/tosa-to-linalg/conv_pad.tgt.mlir
tests/long-opts/tosa-to-linalg/depthwise2.tgt.mlir

Before: `linalg.fill(%in, %out): inTy, outTy`
After: `linalg.fill ins(%in: inTy) outs(%out: outTy)`

Fix `linalg.fill` operands to follow the updated syntax

---

src/abstractops.cpp

This PR updates the semantics of fp addition to yield the value of appropriate sign.
Thanks to recent updates regarding the cmpf, we can determine the sign of the sum between finite values of different sign: we follow the sign of the value with greater magnitude.

Give more precise semantics to fp add

---

.github/workflows/run-test.yml

Due to a bug in MLIR (see [here](https://github.com/llvm/llvm-project/issues/55010)), building mlir-tv in release mode fails.
Disable building in release mode until this bug is fixed.

Temporarily disable build-release CI

---

src/analysis.cpp
src/encode.cpp

Some of the getter methods in MLIR have been changed from `<something>` to `get<Something>`.
This patch applies these API changes into the mlir-tv codebase.

Catch up with the latest MLIR

---

.github/workflows/run-test.yml
CMakeLists.txt

This patch introduces a number of **very critical** braking changes. They will be described in more details below.
CMake function `find_package()` is very powerful. It can automatically locate the specified library in the system if it exists, and even provides several helper variables.
This patch implements automatic dependency resolution using this function. Users won't have to manually specify the `MLIR_DIR`, `Z3_DIR`, and `CVC5_DIR` anymore. In fact, they **must not** be manually set, as they are configured by the `find_package()` function. **Overriding these variables may yield completely unexpected result.**
If the user has multiple versions of these libraries in their system and has to use a specific version of them, they should use `MLIR_ROOT`, `Z3_ROOT`, and `cvc5_ROOT` (cvc …

Refactor & clean-up CMakeLists

---

src/smt.cpp
src/smt.h

This PR implements `shl`, `ashr`, and `lshr` methods for `smt::Expr`.
* `Expr::shl(const unsigned bits) const` yields a new BV of the same sort with `bits` bits shifted to the left.
* `Expr::ashr(const unsigned bits) const` yields a new BV of the same sort with `bits` bits shifted to the right. Higher bits are filled with 1 if the MSB of the original BV was 1, and 0 otherwise.
* `Expr::lshr(const unsigned bits) const` yields a new BV of the same sort with `bits` bits shifted to the right. Higher bits are always filled with 0.

Implement bit shift for `smt::Expr`

---

.gitignore

clangd creates .cache directory and places code analysis cache in there.
This PR adds this directory to `.gitignore`

Add clangd cache directory to `.gitignore`

---

.gitignore
src/encode.cpp

This PR fetches some new features in master into heaan-mlir branch.
* Add `.cache` (clangd cache directory) to `.gitignore`
It seems that 'merging' the master into another branch tries to apply every change made to master since the split, thus overriding the resolved merge conflicts from the previous merge PR.
Fetching updates from master should be done via 'cherry-picking' from the next PR.

Fetch updates from master

---

tests/litmus/func-ops/scalar.src.mlir
tests/litmus/func-ops/scalar.tgt.mlir

Some tests for scalar function calls were renamed to better represent their goals.

Rename misleading tests

---

.github/workflows/run-test.yml
README.md

The LLVM bug that caused build-release CI to fail [is fixed](https://github.com/llvm/llvm-project/commit/49157fd468521ee482d3f5a0ae1586f9d7c8a550)

Re-enable build-release CI

---

src/function.cpp
src/function.h
src/value.cpp
src/value.h
tests/litmus/func-ops/cast_to_dyn-bad.src.mlir
tests/litmus/func-ops/cast_to_dyn-bad.tgt.mlir
tests/litmus/func-ops/tensor-bad.src.mlir
tests/litmus/func-ops/tensor-bad.tgt.mlir
tests/litmus/func-ops/tensor.src.mlir
tests/litmus/func-ops/tensor.tgt.mlir

This PR lifts some restriction of encoding for scalar function call.
As of now, mlir-tv can encode very limited set of functions that succeeds to meet the following criterias.
* Function must have only one return value
* Function operand(s) must be zero or more scalar (int, float, index) value(s)
* Function must return a scalar value **or a ~~fixed-size~~ ranked tensor** // updated in this PR
More restrictions are to be lifted in the further PRs.

Implement encoding for function calls with dynamic tensors

---

tests/litmus/memref-ops/memref-arg-stride.src.mlir
tests/litmus/memref-ops/memref-arg-stride.tgt.mlir
tests/litmus/memref-ops/subview_out_of_bounds.src.mlir
tests/opts/fold-memref-subview-op/rank_reduction.src.mlir

The syntax for the strided layout has been changed.
Also, according to [this documentation](https://mlir.llvm.org/docs/Dialects/Builtin/#strided-layout) strided layout cannot be implicitly converted to affine layout anymore. The deleted tests became invalid due to this change.

Update tests to use the new MLIR strided layout syntax

---

.github/workflows/run-test.yml
tests/lit/formats/mlirtest.py

Parsing error messages are shown on stderr, which is not captured by ctest and therefore does not appear on the test log.
This patch updates the lit test script to redirect both stdout and stderr to stdout when a parsing error is thrown.
`--output-on-failure` is added to show the error on Actions log as well. Hopefully we won't have to download the log file anymore for most of the time.

Print stdout and stderr upon parsing failure

---

src/encode.cpp
src/function.cpp
src/function.h
tests/litmus/func-ops/fn_arg_dims.src.mlir
tests/litmus/func-ops/fn_arg_dims.tgt.mlir
tests/litmus/func-ops/fn_arg_dims_multiple.src.mlir
tests/litmus/func-ops/fn_arg_dims_multiple.tgt.mlir
tests/litmus/func-ops/no_fn_arg_dims-bad.src.mlir
tests/litmus/func-ops/no_fn_arg_dims-bad.tgt.mlir

This PR adds a command-line option `--use-fn-argument-dims`. This option can be used to make an assumption on the shape of the dynamic tensor from a function call.
This option can be used as the following:
* `--use-fn-argument-dims=simpl_fn@0` (the output tensor from `simpl_fn` is assumed to have the same shape as the first argument)
* `--use-fn-argument-dims=fn1@2,fn2@4` (the output tensor from `fn1` is assumed to have the same shape as its third argument, and for `fn2` its fifth argument)
When using this option, UnsupportedException may be thrown under the following circumstances:
* The index used to specify the argument is invalid
* The specified argument or the output type is not shaped
* The output type is unranked or its rank does not match the specified argument
* The shape of the …

Add command-line option `--use-fn-argument-dims`

---

src/encode.cpp
tests/litmus/arith-ops/shift.src.mlir
tests/litmus/arith-ops/shift.tgt.mlir
tests/litmus/arith-ops/shli_index_ub.src.mlir
tests/litmus/arith-ops/shli_index_ub.tgt.mlir
tests/litmus/arith-ops/shli_tensor_ub.src.mlir
tests/litmus/arith-ops/shli_tensor_ub.tgt.mlir
tests/litmus/arith-ops/shli_ub.src.mlir
tests/litmus/arith-ops/shli_ub.tgt.mlir
tests/litmus/arith-ops/shrsi_ub.src.mlir
tests/litmus/arith-ops/shrsi_ub.tgt.mlir
tests/litmus/arith-ops/shrui_ub.src.mlir
tests/litmus/arith-ops/shrui_ub.tgt.mlir

This PR implements encoding for integer shift operations(`arith.shli`, `arith.shrsi`, `arith.shrui`)
* `arith.shli` shifts an integer to the left by a given amount, and fills the 'low-order bits' with 0. `arith.shli %i, %amnt` is equivalent to `arith.mul %i, (math.ipowi 2, %amnt)`
* `arith.shrsi` shifts an integer to the right by a given amount, and fills the 'high-order bits' with the MSB. `arith.shrsi %i, %amnt` is equivalent to `arith.divsi %i, (math.ipowi 2, %amnt)`
* `arith.shrui` shifts an integer to the right by a given amount, and fills the 'high-order bits' with 0. `arith.shrui %i, %amnt` is equivalent to `arith.divui %i, (math.ipowi 2, %amnt)`
If the shift amount is greater than or equal to the integer's bitwidth, it *seems to be* UB. We don't have any official documentation to …

Encoding for integer shift operations

---

src/encode.cpp
src/value.cpp
tests/litmus/arith-ops/extsi.src.mlir
tests/litmus/arith-ops/extsi.tgt.mlir
tests/litmus/arith-ops/extui.src.mlir
tests/litmus/arith-ops/extui.tgt.mlir
tests/litmus/fp-ops/ext_const.src.mlir
tests/litmus/fp-ops/ext_const.tgt.mlir
tests/litmus/fp-ops/trunc_const.src.mlir
tests/litmus/fp-ops/trunc_const.tgt.mlir

This PR extends the encoding for extension(`arith.extf`, `arith.extsi`, `arith.extui`) and truncation(`arith.truncf`, `arith.trunci`) to support programs that use these operations with tensor operands.
When using these operations with tensor operands, they are expected to yield a tensor of the same dimensions, with extension/truncation applied elementwise.
More tests are added to test and verify the behavior.

Encoding for extension and truncation of tensors

---

.github/workflows/run-test.yml

The forks of mlir-tv (and PRs from them) were unable to run CI due to the use of repo-private secrets.
This PR removes all uses of the secrets to lift such restrictions.
Creating the CI image still uses these secrets. It shouldn't be run by the forks.

Remove all uses of secret from CI script
