src/value.cpp
This may contradicts with #32 (comment).
But in mlir documents (https://mlir.llvm.org/docs/Dialects/Builtin/#index-map), the index space is always non-negative and integral. So it is not allowed to access with negative Index.
Also MemRef's dimension-wise indices should be strictly checked in MLIR, although it is not the case in C array semantic (like below example)
```
<MLIR>
func @something(%arg : memref<5x10xf32>) -> f32 {
%1 = memref.load %0[7, 1] : memref<5x10xf32> // It is not allowed!!
}
<C>
int arr[5][10];
int x = arr[7][1]; // 7 * 5 + 1 = 36 < 50, So it's not UB in C
```
`mlir::boundCheckLoadOrStoreOp` in mlir/lib/Analysis/Utils.cpp may relate with this.
So we need this bound checks in well-defineness.
=> Implement dimension-wise inbounds check for Memref

src/vcgen.cpp
Fix typo in checking `hasQuantifier`.
=> Fix bug in smt-solver logic selection

src/encode.cpp, src/state.cpp, src/value.cpp
=> Resolve compiler warnings

src/encode.cpp, src/smt.cpp, src/smt.h, tests/litmus/tosa-ops/bitwise_and.src.mlir, tests/litmus/tosa-ops/bitwise_and.tgt.mlir, tests/litmus/tosa-ops/bitwise_and2.src.mlir, tests/litmus/tosa-ops/bitwise_and2.tgt.mlir, tests/litmus/tosa-ops/bitwise_broadcast.src.mlir, tests/litmus/tosa-ops/bitwise_broadcast.tgt.mlir, tests/litmus/tosa-ops/bitwise_not.src.mlir, tests/litmus/tosa-ops/bitwise_not.tgt.mlir, tests/litmus/tosa-ops/bitwise_or.src.mlir, tests/litmus/tosa-ops/bitwise_or.tgt.mlir, tests/litmus/tosa-ops/bitwise_or2.src.mlir, tests/litmus/tosa-ops/bitwise_or2.tgt.mlir, tests/litmus/tosa-ops/bitwise_xor.src.mlir, tests/litmus/tosa-ops/bitwise_xor.tgt.mlir, tests/litmus/tosa-ops/bitwise_xor2.src.mlir, tests/litmus/tosa-ops/bitwise_xor2.tgt.mlir
implemented bitwise and, not, or, xor operations
=> Implement tosa.bitwise operations

src/main.cpp, tests/lit/formats/mlirtest.py, tests/long-opts/llvmcpu-plan-conv-loop-order/simple-bad.src.mlir, tests/long-opts/llvmcpu-plan-conv-loop-order/simple.src.mlir
Set tv's timeout to 30000ms and give more generous timeout in some long-opts examples.
=> Set default timeout to 30000ms

src/analysis.cpp
Analyzing process also consider linalg.generic inner loop.
=> Analyze constant floating number in linalg.generic loop

src/analysis.cpp, src/analysis.h, src/main.cpp, src/vcgen.cpp
Determine the number of memblocks based on memref counts in program. (very conservative assumption)
=> Support dynamic memblock counts

src/abstractops.cpp
resolve https://github.com/aqjune/mlir-tv/issues/202 issues.
=> Avoid the LSB of addf, mulf value being unconditionally 0 if two operands are equal

src/encode.cpp, tests/litmus/tensor-ops/insert_slice1.src.mlir
=> Sync insert_slice with the updated MLIR

src/abstractops.cpp, src/abstractops.h, tests/litmus/linalg-loops/sum-unit-tensor.src.mlir, tests/litmus/linalg-loops/sum-unit-tensor.tgt.mlir
=> Support basic sum_fn equality

src/encode.cpp, tests/litmus/tosa-ops/gather.src.mlir, tests/litmus/tosa-ops/gather.tgt.mlir, tests/litmus/tosa-ops/gather_unknown_size.src.mlir, tests/litmus/tosa-ops/gather_unknown_size.tgt.mlir
=> Implement tosa.gather ops

src/smt.cpp
CVC5 constructs a new constant or variable even when we call mkConst() or mkVar() with the same name.
We want to obtain the preconstructed term when we call these methods with same name (like Z3), so this PR manually implements this behavior by keeping a map inside smt::Context.
=> Unify the behavior of Expr::mkVar() between Z3 and cvc5

src/encode.cpp, tests/litmus/tosa-ops/conv2d1.src.mlir, tests/litmus/tosa-ops/conv2d2.src.mlir, tests/litmus/tosa-ops/conv2d2.tgt.mlir, tests/litmus/tosa-ops/conv2d3.src.mlir, tests/litmus/tosa-ops/conv2d3.tgt.mlir, tests/litmus/tosa-ops/conv2d4.src.mlir, tests/litmus/tosa-ops/conv2d4.tgt.mlir, tests/litmus/tosa-ops/conv2d5.src.mlir, tests/litmus/tosa-ops/conv2d5.tgt.mlir
fix bugs & add test cases for tosa.conv2d
=> Fix bugs and add test cases for tosa.conv2d

src/encode.cpp
=> Add UB condition for tosa.conv2d and tosa.depthwise_conv2d

src/encode.cpp, tests/opts/tosa-make-broadcastable/broadcast1.src.mlir, tests/opts/tosa-make-broadcastable/broadcast1.tgt.mlir
=> Debug tosa's broadcast operation

.github/workflows/env.yml
=> Only use stable tags for solvers

.github/workflows/env.yml
=> Revert "Only use stable tags for solvers"

src/encode.cpp, src/smt.cpp, src/value.cpp, src/value.h
optimize convolution operation
=> Optimize convolution operations

src/encode.cpp, src/value.cpp, src/value.h
Only below cases use positive zero fp value
- tosa padded tensor (padded with +0.0 values)
- sparse tensor
=> Fix fp identity related issue

src/abstractops.cpp, src/abstractops.h, src/vcgen.cpp
=> Add options for check shape only

src/encode.cpp
=> Support memref type for linalg.depthwise_conv_2d_nhwc_hwcm

src/encode.cpp, tests/opts/linalg-bufferize/depthwise1.src.mlir, tests/opts/linalg-bufferize/depthwise1.tgt.mlir, tests/opts/linalg-bufferize/depthwise2.src.mlir, tests/opts/linalg-bufferize/depthwise2.tgt.mlir
=> Add tests for linalg.depthwise_conv_2d_nhwc_hwcm

src/encode.cpp, src/value.cpp, src/value.h, tests/opts/linalg-canonicalize/from_elem1.src.mlir, tests/opts/linalg-canonicalize/from_elem1.tgt.mlir, tests/opts/linalg-canonicalize/from_elem2.src.mlir, tests/opts/linalg-canonicalize/from_elem2.tgt.mlir
=> Fix crash test cases

src/encode.cpp, tests/litmus/linalg-ops/pooling_unsupported1.src.mlir, tests/litmus/linalg-ops/pooling_unsupported1.tgt.mlir, tests/litmus/linalg-ops/pooling_unsupported2.src.mlir, tests/litmus/linalg-ops/pooling_unsupported2.tgt.mlir
=> Fix crash for integer element tensor

.github/workflows/env.yml
=> Fix ci image update script

.github/workflows/env-heaan.yml, .github/workflows/run-test.yml
Add a separate image build script for heaan branch.
This will allow non-MLIR API related changes to be applied more easily.
=> Separate CI image for heaan branch
